services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=oso_cart
    volumes:
      - flask-demo-db-volume:/var/lib/postgresql/data
    ports:
      - "5444:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 1s
      timeout: 2s
      retries: 10
  oso:
    image: public.ecr.aws/osohq/dev-server:latest
    command: --watch-for-changes /cfg/policy.polar
    volumes:
      - ./authorization:/cfg
      - ./.oso:/data
    ports:
      - "9090:8080"
  app:
    build:
      dockerfile: Dockerfile.app
    environment:
      FLASK_RUN_HOST: 0.0.0.0
      FLASK_RUN_PORT: 5000
      FLASK_DEBUG: true
      FLASK_ENVIRONMENT: development
      FLASK_APP: oso_demo:create_app
      DATABASE_URL: postgresql://postgres:postgres@db:5432/oso_cart
      OSO_AUTH: e_0123456789_12345_osotesttoken01xiIn
      OSO_URL: http://oso:9090
    ports:
      - "5000:5000"
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
volumes:
  flask-demo-db-volume:
    name: flask-demo-db-volume