"""empty message

Revision ID: 38cd54e9d057
Revises: 02e3b181da9f
Create Date: 2025-05-02 15:42:20.576363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38cd54e9d057'
down_revision = '02e3b181da9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_public', sa.Boolean(), nullable=False))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shops', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('is_public')

    # ### end Alembic commands ###
